[package]
name = "coffee-api"
version = "0.1.0"
edition = "2021"

[dependencies]
migrate = "^0.2.0"
sqlx = "^0.7.3"
sqlx-core = "^0.7.3"
sqlx-macros = "^0.7.3"
sqlx-mysql = "^0.7.3"
sqlx-postgres = "^0.7.3"
sqlx-sqlite = "^0.7.3"